# Generated by Django 5.1.6 on 2025-02-08 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IM', '0002_rename_proveedor_producto_proveedorproductoscore_provedor_producto'),
        ('SCM', '0004_rename_cost_dropping_provedor_cost_dropping_score_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='provedor_producto',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='provedor_producto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider', to='IM.producto_hijo'),
        ),
        migrations.AddConstraint(
            model_name='provedor_producto',
            constraint=models.UniqueConstraint(fields=('producto', 'provedor'), name='unique_proveedor_producto'),
        ),
    ]
