# Generated by Django 5.1.6 on 2025-02-08 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SCM', '0003_purchaseorderitem_supplier_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provedor',
            old_name='cost_dropping',
            new_name='cost_dropping_score',
        ),
        migrations.RenameField(
            model_name='provedor',
            old_name='credit',
            new_name='credit_score',
        ),
        migrations.RenameField(
            model_name='provedor',
            old_name='fiability',
            new_name='fiability_score',
        ),
    ]
